name: Continuous Delivery

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Gerar artefato zipado
        run: |
          mkdir entrega
          cp Program.cs entrega/
          cp Program.csproj entrega/
          cp README.md entrega/
          zip -r projeto.zip entrega

      - name: Upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: projeto-entregue
          path: projeto.zip
