name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'  # Use a versão do seu projeto

      - name: Restaurar dependências
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Testes
        run: dotnet test --no-build --verbosity normal
